modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/starforcraft/Creative-Wireless-Transmitter/issues"
license = "MIT"
[[mods]]
modId = "creativewirelesstransmitter"
version = "${version}"
displayName = "Creative Wireless Transmitter"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter"
logoFile="logo.png"
authors = "Ultramega"
description = "Creative Wireless Transmitter is an addon for Refined Storage which adds a cross-dimensional transmitter with infinite range."

[[dependencies.creativewirelesstransmitter]]
modId = "refinedstorage"
type = "required"
versionRange = "2.0.0-milestone.4.10"
side = "BOTH"
